// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © claygrace74


study(title="Bears and Bulls", overlay=true)
body=close-open
range=high-low
middle=(open+close)/2
abody=abs(body)
ratio=abody/range
longcandle= (ratio>0.6)
bodytop=max(open, close)
bodybottom=min(open, close)
shadowtop=high-bodytop
shadowbottom=bodybottom-low

//Define Bearish Candle Patterns ******************************************************

evening_star = (close[2] > open[2] and abs(close[2] - open[2])/(high[2] - low[2]) >= 0.7 and 0.3 > abs(close[1] - open[1]) / (high[1] - low[1]) >= 0.1 and close < open and abs(close - open) / (high-low) >= 0.7 and close[2] < close[1] and close[2] < open[1] and close[1] > open and open[1] > open and close < close[2])
evening_star_doji = (close[2]>open[2] and abs(close[2]-open[2])/(high[2]-low[2])>=0.7 and abs(close[1]-open[1])/(high[1]-low[1])<0.1 and close<open and abs(close-open)/(high-low)>=0.7 and close[2]<close[1] and close[2]<open[1] and close[1]>open and open[1]>open and close<close[2] and (high[1]-max(close[1],open[1]))>(3*abs(close[1]-open[1])) and (min(close[1],open[1])-low[1])>(3*abs(close[1]-open[1])))
shooting_star=(body[1]>0 and longcandle[1] and high>high[1] and shadowtop>2*abody and shadowbottom<0.3*abody)
shooting_star_doji=(close[1]>open[1] and abs(close[1]-open[1])/(high[1]-low[1])>=0.7 and abs(close-open)/(high-low)<0.1 and close[1]<close and close[1]<open and (high-max(close,open))>(3*abs(close-open)) and (min(close,open)-low)>(3*abs(close-open)))
dark_cloud_cover=(close[1]>open[1] and abs(close[1]-open[1])/(high[1]-low[1])>=0.7 and close<open and abs(close-open)/(high-low)>=0.7 and open>=close[1] and close>open[1] and close<((open[1]+close[1])/2))
the_hanging_man=(close<open and 0.3>abs(close-open)/(high-low)>=0.1 and (min(close,open)-low)>=(2*abs(close-open)) and (high-max(close,open))>(0.25*abs(close-open)))
bearish_engulfing=(close[1]>open[1] and 0.3>abs(close[1]-open[1])/(high[1]-low[1])>=0.1 and close<open and abs(close-open)/(high-low)>=0.7 and high[1]<open and low[1]>close)
bearish_engulfing_doji=(abs(close[1]-open[1])/(high[1]-low[1])<0.1 and close>open and abs(close-open)/(high-low)>=0.7 and high[1]<close and low[1]>open and (high[1]-max(close[1],open[1]))>(3*abs(close[1]-open[1])) and (min(close[1],open[1])-low[1])<=abs(close[1]-open[1]))
bearish_harami=(body[1]>0 and body<0 and longcandle[1] and bodybottom>bodybottom[1] and bodytop<bodytop[1])
falling_three_methods=(body[4]<0 and body[3]>0 and body[1]>0 and body<0 and longcandle[4] and longcandle and close[2]>close[3] and close[1]>close[2] and low[2]>low[3] and low[1]>low[2] and high[1]<high[4] and open<close[1] and close<low[4] and close<low[3] and close<low[2] and close<low[1])
bearish_harami_cross=(body[1]>0 and longcandle[1] and bodybottom>bodybottom[1] and bodytop<bodytop[1] and ratio<0.3 and range<0.3*range[1])
three_inside_down=(body[2]>0 and body[1]<0 and body<0 and bearish_harami[1] and close<close[1])
last_engulfing_top=(body[1]<0 and body>0 and bodybottom<bodybottom[1] and bodytop>bodytop[1] and longcandle)
bearish_three_line_strike=(body[3]<0 and body[2]<0 and body[1]<0 and body>0 and longcandle[3] and longcandle[2] and longcandle[1] and close[2]<close[3] and close[1]<close[2] and open<close[1] and close>open[3])
gravesstone_doji_top=(body[1]>0 and longcandle[1] and high>high[1] and shadowtop>3*abody and shadowbottom<shadowtop/3)
//
abandoned_baby_top=(body[2]>0 and body<0 and longcandle[2] and ratio[1]<0.3 and low[1]>high[2] and low[1]>high)
descending_hawk=(body[1]>0 and body>0 and longcandle[1] and bodybottom>bodybottom[1] and bodytop<bodytop[1])
three_outside_down=(body[2]>0 and body[1]<0 and body<0 and bearish_engulfing[1] and close<close[1])
three_black_crows=(body[2]<0 and body[1]<0 and body<0 and longcandle[2] and longcandle[1] and longcandle and low[1]<low[2] and low<low[1] and close[1]<close[2] and close<close[1] and open[1]<open[2] and open[1]>close[2] and open<open[1] and open>close[1])
upside_gap_two_crows=(body[2]>0 and body[1]<0 and body<0 and longcandle[2] and open[1]>close[2] and bodytop>bodytop[1] and bodybottom<bodybottom[1] and close>close[2])
dragonfly_doji_top=(body[1]>0 and longcandle[1] and high>high[1] and shadowbottom>3*abody and shadowtop<shadowbottom/3)
advance_block=(body[2]>0 and body[1]>0 and body>0 and high[2]<high[1] and high[1]<high and open[1]>bodybottom[2] and open[1]<bodytop[2] and open>bodybottom[1] and open<bodytop[1] and abody[1]<abody[2] and abody<abody[1])
bearish_breakaway=(body[4]>0 and body[3]>0 and body<0 and open[3]>close[4] and close[2]>close[3] and close[1]>close[2] and longcandle and close>close[4] and close<open[3])
two_crows=(body[2]>0 and body[1]<0 and body<0 and longcandle[2] and open[1]>close[2] and close[1]>close[2] and open<bodytop[1] and open>bodybottom[1] and close<bodytop[2] and close>bodybottom[2])

// Define Bullish Candle Patterns
morning_star=(close[2]<open[2] and abs(close[2]-open[2])/(high[2]-low[2])>=0.7 and 0.3>abs(close[1]-open[1])/(high[1]-low[1])>=0.1 and close>open and abs(close-open)/(high-low)>=0.7 and close[2]>close[1] and close[2]>open[1] and close[1]<open and open[1]<open and close>close[2])
morning_star_doji=(close[2]<open[2] and abs(close[2]-open[2])/(high[2]-low[2])>=0.7 and abs(close[1]-open[1])/(high[1]-low[1])<0.1 and close>open and abs(close-open)/(high-low)>=0.7 and close[2]>close[1] and close[2]>open[1] and close[1]<open and open[1]<open and close>close[2] and (high[1]-max(close[1],open[1]))>(3*abs(close[1]-open[1])) and (min(close[1],open[1])-low[1])>(3*abs(close[1]-open[1])))
piercing_line=(close[1]<open[1] and abs(close[1]-open[1])/(high[1]-low[1])>=0.7 and close>open and abs(close-open)/(high-low)>=0.7 and open<=close[1] and close<open[1] and close<((open[1]+close[1])/2))
bullish_harami=(close[1]<open[1] and abs(close[1]-open[1])/(high[1]-low[1])>=0.7 and 0.3>abs(close-open)/(high-low)>=0.1 and high<open[1] and low>close[1])
bullish_engulfing=(body[1]<0 and body>0 and bodybottom<bodybottom[1] and bodytop>bodytop[1] and longcandle)
bullish_engulfing_doji=(abs(close[1]-open[1])/(high[1]-low[1])<0.1 and close>open and abs(close-open)/(high-low)>=0.7 and high[1]<close and low[1]>open and (high[1]-max(close[1],open[1]))>(3*abs(close[1]-open[1])) and (min(close[1],open[1])-low[1])<=abs(close[1]-open[1]))
bullish_harami_cross=(body[1]<0 and longcandle[1] and bodybottom>bodybottom[1] and bodytop<bodytop[1] and ratio<0.3 and range<0.3*range[1])
three_white_soldiers=(body[2]>0 and body[1]>0 and body>0 and high[1]>high[2] and high>high[1] and close[1]>close[2] and close>close[1] and open[1]>open[2] and open[1]<close[2] and open>open[1] and open<close[1])
bullish_breakaway=(body[4]<0 and body[3]<0 and body>0 and open[3]<close[4] and close[2]<close[3] and close[1]<close[2] and longcandle and close<close[4] and close>open[3])
three_stars_in_the_south=(body[2]<0 and body[1]<0 and body<0 and shadowtop[2]<range[2]/4 and shadowbottom[2]>abody[2]/2 and low[1]>low[2] and high[1]<high[2] and abody[1]<abody[2]  and shadowtop[1]<range[1]/4 and shadowbottom[1]>abody[1]/2 and low>low[1] and high<high[1] and abody<abody[1] and shadowtop<range/4 and shadowbottom<range/4)
last_engulfing_bottom=(body[1]>0 and body<0 and bodybottom<bodybottom[1] and bodytop>bodytop[1] and longcandle)
//
bullish_mat_hold=(body[4]>0 and body[3]<0 and body[1]<0 and body>0 and longcandle[4] and close[3]>close[4] and close[2]<close[3] and close[1]<close[2] and high[2]<high[3] and high[1]<high[2] and low[1]>low[4] and open>close[1] and close>high[4] and  close>high[3] and close>high[2] and close>high[1])
rising_three_methods=(body[4]>0 and body[3]<0 and body[1]<0 and body>0 and longcandle[4] and longcandle and close[2]<close[3] and close[1]<close[2] and high[2]<high[3] and high[1]<high[2] and low[1]>low[4] and open>close[1] and close>high[4] and close>high[3] and close>high[2] and close>high[1])
bullish_three_line_strike=(body[3]>0 and body[2]>0 and body[1]>0 and body<0 and longcandle[3] and longcandle[2] and longcandle[1] and close[2]>close[3] and close[1]>close[2] and open>close[1] and close<open[3])
hammer=(body[1]<0 and longcandle[1] and low<low[1] and shadowbottom>2*abody and shadowtop<0.3*abody)
inverted_hammer=(body[1]<0 and longcandle[1] and low<low[1] and shadowtop>2*abody and shadowbottom<0.3*abody)
concealing_baby_swallow=(body[3]<0 and body[2]<0 and body[1]<0 and body<0 and ratio[3]>0.8 and ratio[2]>0.8 and ratio>0.8 and open[1]<close[2] and high[1]>close[2] and shadowtop[1]>0.6*(abody[1]+shadowbottom[1]) and bodybottom<bodybottom[1] and bodytop>high[1])
dragonfly_doji_bottom=(body[1]<0 and longcandle[1] and low<low[1] and shadowbottom>3*abody and shadowtop<shadowbottom/3)
homing_pigeon=(body[1]<0 and body<0 and longcandle[1] and bodybottom>bodybottom[1] and bodytop<bodytop[1])
three_outside_up=(body[2]<0 and body[1]>0 and body>0 and bullish_engulfing[1] and close>close[1])
three_inside_up=(body[2]<0 and body[1]>0 and body>0 and bullish_harami[1] and close>close[1])
abandoned_baby_bottom=(body[2]<0 and body>0 and longcandle[2] and ratio[1]<0.3 and high[1]<low[2] and high[1]<low)




// ************************************************************************************
// Calculate if the RSI is high or low
// Modified version of rsi function from https://zenandtheartoftrading.com/pinescript/generate-trading-signals-with-rsi/
// Config ---------------------------------------


rsisrc = close
rsilen = 14
rsiob = 60
rsios = 50
rsihighclr = #F90404FF
rsilowclr = #04F909FF

// Action --------------------------------------
rsival = rsi(rsisrc, rsilen)
isrsiob = (rsival >= rsiob)
isrsios = (rsival <= rsios)
bullengulf = close > open[1] and close[1] < open[1]
bearengulf = close < open[1] and close[1] > open[1]

rsisignal = ((isrsios or isrsios[1]) and bullish_engulfing) or 
    ((isrsios or isrsios[1]) and last_engulfing_bottom) or 
    ((isrsios or isrsios[1]) and bullish_breakaway) or 
    ((isrsios or isrsios[1]) and three_stars_in_the_south) or 
    ((isrsios or isrsios[1]) and three_white_soldiers) or 
    ((isrsios or isrsios[1]) and bullish_harami_cross) or 
    ((isrsios or isrsios[1]) and bullish_engulfing_doji) or 
    ((isrsios or isrsios[1]) and bullish_harami) or 
    ((isrsios or isrsios[1]) and piercing_line) or 
    ((isrsios or isrsios[1]) and inverted_hammer) or 
    ((isrsios or isrsios[1]) and morning_star_doji) or 
    ((isrsios or isrsios[1]) and morning_star) or 
    ((isrsios or isrsios[1]) and bullish_mat_hold) or
    ((isrsios or isrsios[1]) and rising_three_methods) or
    ((isrsios or isrsios[1]) and bullish_three_line_strike) or
    ((isrsios or isrsios[1]) and hammer) or
    ((isrsios or isrsios[1]) and concealing_baby_swallow) or
    ((isrsios or isrsios[1]) and dragonfly_doji_bottom) or
    ((isrsios or isrsios[1]) and homing_pigeon) or
    ((isrsios or isrsios[1]) and three_outside_up) or
    ((isrsios or isrsios[1]) and three_inside_up) or
    ((isrsios or isrsios[1]) and abandoned_baby_bottom) or
    ((isrsiob or isrsiob[1]) and bearish_engulfing) or 
    ((isrsiob or isrsiob[1]) and bearish_engulfing_doji) or 
    ((isrsiob or isrsiob[1]) and bearish_harami) or 
    ((isrsiob or isrsiob[1]) and the_hanging_man) or 
    ((isrsiob or isrsiob[1]) and falling_three_methods) or 
    ((isrsiob or isrsiob[1]) and last_engulfing_top) or 
    ((isrsiob or isrsiob[1]) and bearish_three_line_strike) or 
    ((isrsiob or isrsiob[1]) and three_inside_down) or 
    ((isrsiob or isrsiob[1]) and gravesstone_doji_top) or 
    ((isrsiob or isrsiob[1]) and dark_cloud_cover) or 
    ((isrsiob or isrsiob[1]) and shooting_star) or 
    ((isrsiob or isrsiob[1]) and shooting_star_doji) or 
    ((isrsiob or isrsiob[1]) and bearish_harami_cross) or 
    ((isrsiob or isrsiob[1]) and evening_star) or 
    ((isrsiob or isrsiob[1]) and abandoned_baby_top) or
    ((isrsiob or isrsiob[1]) and descending_hawk) or
    ((isrsiob or isrsiob[1]) and three_outside_down) or
    ((isrsiob or isrsiob[1]) and three_black_crows) or
    ((isrsiob or isrsiob[1]) and upside_gap_two_crows) or
    ((isrsiob or isrsiob[1]) and dragonfly_doji_top) or
    ((isrsiob or isrsiob[1]) and advance_block) or
    ((isrsiob or isrsiob[1]) and bearish_breakaway) or
    ((isrsiob or isrsiob[1]) and two_crows) or
    ((isrsiob or isrsiob[1]) and evening_star_doji)
// plot bullish signals
plotshape(rsisignal and bullish_engulfing, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
plotshape(rsisignal and bullish_engulfing_doji, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
plotshape(rsisignal and bullish_harami, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
plotshape(rsisignal and piercing_line, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
plotshape(rsisignal and inverted_hammer, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
plotshape(rsisignal and morning_star, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
plotshape(rsisignal and morning_star_doji, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
plotshape(rsisignal and bullish_harami_cross, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
plotshape(rsisignal and three_white_soldiers, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
plotshape(rsisignal and bullish_breakaway, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
plotshape(rsisignal and three_stars_in_the_south, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
plotshape(rsisignal and last_engulfing_bottom, style=shape.triangleup, color = rsilowclr, size=size.tiny, location=location.belowbar)
// plot bearish signals.
plotshape(rsisignal and gravesstone_doji_top, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and bearish_three_line_strike, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and last_engulfing_top, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and three_inside_down, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and bearish_harami_cross, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and falling_three_methods, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and bearish_engulfing, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and bearish_engulfing_doji, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and bearish_harami, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and the_hanging_man, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and dark_cloud_cover, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and shooting_star, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and shooting_star_doji, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and evening_star, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
plotshape(rsisignal and evening_star_doji, style=shape.triangledown, color = rsihighclr, size=size.tiny, location=location.abovebar)
