// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © claygrace74

//@version=5
indicator("MacD", overlay = false, timeframe="", timeframe_gaps=true)

var MACD_group =         '===================== MacD Settings ===================='
macdsrc = input.source(title = 'MacD Source', defval = close, group = MACD_group)
int macdfastlen = input.int(title = 'MacD Fast Length', defval = 12, minval = 1, group = MACD_group)
int macdslowlen = input.int(title = 'MacD Slow Length', defval = 26, minval = 1, group = MACD_group)
int macdsignallen = input.int(title = 'MacD Signal Smoothing', defval = 9, minval = 1, maxval = 50, group = MACD_group)
color upmacd = input.color(title = 'MacD Cross Up', defval = #05011d, inline = MACD_group, group = MACD_group)
color downmacd = input.color(title = 'MacD Cross Down', defval = #EF5350, inline = MACD_group, group = MACD_group)
bool i_showMACDcross = input.bool(title = 'Show The MACD Cross', defval = false, group = MACD_group)
// ************************************************************************************
// MacD Cross
// Default - (EMA 12) (EMA 26) (SMA 9)
// ************************************************************************************
fastavg = ta.ema(macdsrc, macdfastlen)
slowavg = ta.ema(macdsrc, macdslowlen)
macd = fastavg - slowavg
macdsignal = ta.ema(macd, macdsignallen)
cross_3 = ta.cross(macdsignal, macd)
macdata = cross_3 ? macdsignal : na
crossover_3 = ta.crossover(macdsignal, macd)
crossunder_3 = ta.crossunder(macdsignal, macd)
macdhist = macd - macdsignal
macddir = crossover_3 ? 'down' : crossunder_3 ? 'up' : na

macdclr = macddir == 'down' ? downmacd : macddir == 'up' ? upmacd : na


trend = macdhist > 0 ? 'Bullish' : 'Bearish'

macd_loc = macddir == 'up' ? "location.abovebar" : "location.belowbar"
hline(0, "Zero Line", color=color.new(#787B86, 50))
plot(macdhist, color = color.rgb(237, 36, 255), linewidth = 1, style = plot.style_columns, title = 'Hist')
plot(macdsignal, color = color.rgb(255, 152, 36, 0), linewidth = 1, style = plot.style_line, title = 'Signal')
plot(macd, color = color.rgb(44, 29, 255), linewidth = 1, style = plot.style_line, title = 'B')
plotshape(i_showMACDcross ? macdata : na, style=shape.circle, color=color.new(macdclr, 0), size=size.tiny, location=location.absolute, title = "MacD Cross")